# hub.docker.com/search
#Definição da imagem
FROM node:14.17.0

#Cria um diretorio onde será rodado a aplicação
WORKDIR /app

#Copia package.json para dentro do diretorio (acima)
COPY package*.json ./

#Roda npm para baixar as denpedencias
RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["npm", "run", "dev"]