version: "3.8"

services:
  database:
    image: postgres:9.6
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=wallet
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    env_file: .env.dev
    container_name: wallet-backend
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
    networks:
      - default

networks:
  wallet-backend_default:
